description: "A new Flutter project."
name: "hydro_sdk"
version: "1.0.0+1"
dependencies: 
  analyzer: "^0.40.3"
  args: "1.6.0"
  benchmark_harness: "any"
  build_runner: "^1.10.1"
  collection: "any"
  cupertino_icons: "^0.1.2"
  http: "0.12.2"
  json_serializable: "3.5.0"
  recase: "^3.0.0"
  tuple: "^1.0.2"
  flutter: 
    sdk: "flutter"
  surveyor: 
    git: 
      ref: "8d5743560c55bb09f1373aa70c2066b54772f0b5"
      url: "git://github.com/chgibb/surveyor"
  waveform: 
    git: 
      ref: "0.0.1-nightly.19"
      url: "git://github.com/hydro-sdk/waveform.git"
  code_builder: null
  dart_style: null
  freezed: null
  freezed_annotation: null
dev_dependencies: 
  test: "any"
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.9.0 <3.0.0"
flutter: 
  uses-material-design: true
