description: "A new Flutter project."
name: "hydro_sdk"
version: "1.0.0+1"
dependencies:
  analyzer: "^0.40.3"
  args: "1.6.0"
  benchmark_harness: "any"
  build_runner: "^1.10.1"
  collection: "any"
  cupertino_icons: "^0.1.2"
  http: "^0.13.0"
  json_serializable: "3.5.0"
  petitparser: "3.1.0"
  recase: "^3.0.0"
  tuple: "^1.0.2"
  flutter:
    sdk: flutter
  archive: null
  cli_util: null
  code_builder: null
  corsac_jwt: null
  dart_console: null
  dart_style: null
  encrypt: null
  filesize: null
  freezed: null
  freezed_annotation: null
  pointycastle: null
  rsa_pkcs: null
  synchronized: null
  uuid: null
  watcher: null
dev_dependencies:
  import_sorter: "4.4.1"
  test: "any"
  flutter_test:
    sdk: flutter
environment:
  sdk: ">=2.9.0 <3.0.0"
flutter:
  uses-material-design: true
