export type RuntimeType = "AppBar" |
    "AnimatedListState" |
    "FlatButton" |
    "FloatingActionButton" |
    "MaterialApp" |
    "Scaffold" |
    "TextTheme" |
    "Theme" |
    "ThemeData" |
    "TextStyle" |
    "Center" |
    "Column" |
    "GlobalKey" |
    "Icon" |
    "IconData" |
    "MainAxisAlignment" |
    "State" |
    "StatefulWidget" |
    "StatelessWidget" |
    "Text" |
    "EdgeInsets" |
    "Animation" |
    "Key" |
    "PreferredSize" |
    "Color" |
    "Card" |
    "IconButton" |
    "PopupMenuButton" |
    "PopupMenuItem" |
    "AnimatedList" |
    "GestureDetector" |
    "Padding" |
    "SizedBox" |
    "SizeTransition" |
    "Size" |
    "SafeArea" |
    "Stack" |
    "Positioned" |
    "Row" |
    "Flexible" |
    "Container" |
    "Spacer" |
    "BorderRadius" |
    "Radius" |
    "ClipRRect" |
    "Alignment" |
    "Image" |
    "ImageProvider" |
    "NetworkImage" |
    "BoxDecoration" |
    "RichText" |
    "InlineSpan" |
    "Align" |
    "ListView" |
    "SliverChildBuilderDelegate" |
    "Rect" |
    "Offset" | 
    "FontWeight" |
    "MaterialPageRoute" |
    "Expanded" |
    "Gradient" |
    "InkWell" |
    "Transform";

export interface DartObject {
    runtimeType: RuntimeType;
}