import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/baseTapGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/delayedMultiDragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/deviceGestureSettings.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/doubleTapGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/drag.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/dragDownDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/dragEndDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/dragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/dragStartDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/dragUpdateDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/eagerGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/flutterErrorDetailsForPointerEventDispatcher.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/forcePressDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/forcePressGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/gestureArenaEntry.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/gestureArenaManager.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/gestureArenaMember.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/gestureArenaTeam.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/gestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/hitTestDispatcher.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/hitTestEntry.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/hitTestResult.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/hitTestTarget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/hitTestable.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/horizontalDragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/horizontalMultiDragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/iOSScrollViewFlingVelocityTracker.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/immediateMultiDragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/leastSquaresSolver.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/longPressDownDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/longPressEndDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/longPressGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/longPressMoveUpdateDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/longPressStartDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/multiDragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/multiDragPointerState.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/multiTapGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/offsetPair.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/oneSequenceGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/panGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerAddedEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerCancelEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerDownEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerEnterEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerEventConverter.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerEventResampler.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerExitEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerHoverEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerMoveEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerRemovedEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerRouter.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerScrollEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerSignalEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerSignalResolver.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/pointerUpEvent.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/polynomialFit.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/primaryPointerGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/samplingClock.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/scaleEndDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/scaleGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/scaleStartDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/scaleUpdateDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/serialTapCancelDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/serialTapDownDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/serialTapGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/serialTapUpDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/tapDownDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/tapGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/tapUpDetails.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/velocity.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/velocityEstimate.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/velocityTracker.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/verticalDragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/gestures/verticalMultiDragGestureRecognizer.dart';
import 'package:hydro_sdk/cfr/runtimeSupport.dart';

void loadgestures({required HydroState hydroState, required HydroTable table}) {
  final gestures = HydroTable();
  table['gestures'] = gestures;
  loadPolynomialFit(table: gestures, hydroState: hydroState);
  loadLeastSquaresSolver(table: gestures, hydroState: hydroState);
  loadDrag(table: gestures, hydroState: hydroState);
  loadEagerGestureRecognizer(table: gestures, hydroState: hydroState);
  loadGestureArenaTeam(table: gestures, hydroState: hydroState);
  loadDoubleTapGestureRecognizer(table: gestures, hydroState: hydroState);
  loadMultiTapGestureRecognizer(table: gestures, hydroState: hydroState);
  loadSerialTapDownDetails(table: gestures, hydroState: hydroState);
  loadSerialTapCancelDetails(table: gestures, hydroState: hydroState);
  loadSerialTapUpDetails(table: gestures, hydroState: hydroState);
  loadSerialTapGestureRecognizer(table: gestures, hydroState: hydroState);
  loadVelocity(table: gestures, hydroState: hydroState);
  loadVelocityEstimate(table: gestures, hydroState: hydroState);
  loadVelocityTracker(table: gestures, hydroState: hydroState);
  loadIOSScrollViewFlingVelocityTracker(
      table: gestures, hydroState: hydroState);
  loadHitTestable(table: gestures, hydroState: hydroState);
  loadHitTestDispatcher(table: gestures, hydroState: hydroState);
  loadHitTestTarget(table: gestures, hydroState: hydroState);
  loadHitTestEntry(table: gestures, hydroState: hydroState);
  loadHitTestResult(table: gestures, hydroState: hydroState);
  loadTapDownDetails(table: gestures, hydroState: hydroState);
  loadTapUpDetails(table: gestures, hydroState: hydroState);
  loadBaseTapGestureRecognizer(table: gestures, hydroState: hydroState);
  loadTapGestureRecognizer(table: gestures, hydroState: hydroState);
  loadGestureArenaMember(table: gestures, hydroState: hydroState);
  loadGestureArenaEntry(table: gestures, hydroState: hydroState);
  loadGestureArenaManager(table: gestures, hydroState: hydroState);
  loadGestureRecognizer(table: gestures, hydroState: hydroState);
  loadOneSequenceGestureRecognizer(table: gestures, hydroState: hydroState);
  loadPrimaryPointerGestureRecognizer(table: gestures, hydroState: hydroState);
  loadOffsetPair(table: gestures, hydroState: hydroState);
  loadMultiDragPointerState(table: gestures, hydroState: hydroState);
  loadMultiDragGestureRecognizer(table: gestures, hydroState: hydroState);
  loadImmediateMultiDragGestureRecognizer(
      table: gestures, hydroState: hydroState);
  loadHorizontalMultiDragGestureRecognizer(
      table: gestures, hydroState: hydroState);
  loadVerticalMultiDragGestureRecognizer(
      table: gestures, hydroState: hydroState);
  loadDelayedMultiDragGestureRecognizer(
      table: gestures, hydroState: hydroState);
  loadPointerEventConverter(table: gestures, hydroState: hydroState);
  loadForcePressDetails(table: gestures, hydroState: hydroState);
  loadForcePressGestureRecognizer(table: gestures, hydroState: hydroState);
  loadPointerSignalResolver(table: gestures, hydroState: hydroState);
  loadLongPressDownDetails(table: gestures, hydroState: hydroState);
  loadLongPressStartDetails(table: gestures, hydroState: hydroState);
  loadLongPressMoveUpdateDetails(table: gestures, hydroState: hydroState);
  loadLongPressEndDetails(table: gestures, hydroState: hydroState);
  loadLongPressGestureRecognizer(table: gestures, hydroState: hydroState);
  loadDragDownDetails(table: gestures, hydroState: hydroState);
  loadDragStartDetails(table: gestures, hydroState: hydroState);
  loadDragUpdateDetails(table: gestures, hydroState: hydroState);
  loadDragEndDetails(table: gestures, hydroState: hydroState);
  loadScaleStartDetails(table: gestures, hydroState: hydroState);
  loadScaleUpdateDetails(table: gestures, hydroState: hydroState);
  loadScaleEndDetails(table: gestures, hydroState: hydroState);
  loadScaleGestureRecognizer(table: gestures, hydroState: hydroState);
  loadPointerEventResampler(table: gestures, hydroState: hydroState);
  loadPointerEvent(table: gestures, hydroState: hydroState);
  loadPointerAddedEvent(table: gestures, hydroState: hydroState);
  loadPointerRemovedEvent(table: gestures, hydroState: hydroState);
  loadPointerHoverEvent(table: gestures, hydroState: hydroState);
  loadPointerEnterEvent(table: gestures, hydroState: hydroState);
  loadPointerExitEvent(table: gestures, hydroState: hydroState);
  loadPointerDownEvent(table: gestures, hydroState: hydroState);
  loadPointerMoveEvent(table: gestures, hydroState: hydroState);
  loadPointerUpEvent(table: gestures, hydroState: hydroState);
  loadPointerSignalEvent(table: gestures, hydroState: hydroState);
  loadPointerScrollEvent(table: gestures, hydroState: hydroState);
  loadPointerCancelEvent(table: gestures, hydroState: hydroState);
  loadDeviceGestureSettings(table: gestures, hydroState: hydroState);
  loadDragGestureRecognizer(table: gestures, hydroState: hydroState);
  loadVerticalDragGestureRecognizer(table: gestures, hydroState: hydroState);
  loadHorizontalDragGestureRecognizer(table: gestures, hydroState: hydroState);
  loadPanGestureRecognizer(table: gestures, hydroState: hydroState);
  loadSamplingClock(table: gestures, hydroState: hydroState);
  loadFlutterErrorDetailsForPointerEventDispatcher(
      table: gestures, hydroState: hydroState);
  loadPointerRouter(table: gestures, hydroState: hydroState);
}
