import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/buildContext.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/buildOwner.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/componentElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/debugCreator.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/element.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/errorWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/globalKey.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/globalObjectKey.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/indexedSlot.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/inheritedElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/inheritedWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/labeledGlobalKey.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/leafRenderObjectElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/leafRenderObjectWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/multiChildRenderObjectElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/multiChildRenderObjectWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/objectKey.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/parentDataElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/parentDataWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/proxyElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/proxyWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/renderObjectElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/renderObjectWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/rootRenderObjectElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/singleChildRenderObjectElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/singleChildRenderObjectWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/state.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/statefulElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/statefulWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/statelessElement.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/statelessWidget.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/uniqueKey.dart';
import 'package:hydro_sdk/cfr/builtins/libs/flutter/widgets/widget.dart';
import 'package:hydro_sdk/cfr/runtimeSupport.dart';

void loadwidgets({required HydroState hydroState, required HydroTable table}) {
  final widgets = HydroTable();
  table['widgets'] = widgets;
  loadUniqueKey(table: widgets, hydroState: hydroState);
  loadObjectKey(table: widgets, hydroState: hydroState);
  loadGlobalKey(table: widgets, hydroState: hydroState);
  loadLabeledGlobalKey(table: widgets, hydroState: hydroState);
  loadGlobalObjectKey(table: widgets, hydroState: hydroState);
  loadWidget(table: widgets, hydroState: hydroState);
  loadStatelessWidget(table: widgets, hydroState: hydroState);
  loadStatefulWidget(table: widgets, hydroState: hydroState);
  loadState(table: widgets, hydroState: hydroState);
  loadProxyWidget(table: widgets, hydroState: hydroState);
  loadParentDataWidget(table: widgets, hydroState: hydroState);
  loadInheritedWidget(table: widgets, hydroState: hydroState);
  loadRenderObjectWidget(table: widgets, hydroState: hydroState);
  loadLeafRenderObjectWidget(table: widgets, hydroState: hydroState);
  loadSingleChildRenderObjectWidget(table: widgets, hydroState: hydroState);
  loadMultiChildRenderObjectWidget(table: widgets, hydroState: hydroState);
  loadBuildContext(table: widgets, hydroState: hydroState);
  loadBuildOwner(table: widgets, hydroState: hydroState);
  loadElement(table: widgets, hydroState: hydroState);
  loadErrorWidget(table: widgets, hydroState: hydroState);
  loadComponentElement(table: widgets, hydroState: hydroState);
  loadStatelessElement(table: widgets, hydroState: hydroState);
  loadStatefulElement(table: widgets, hydroState: hydroState);
  loadProxyElement(table: widgets, hydroState: hydroState);
  loadParentDataElement(table: widgets, hydroState: hydroState);
  loadInheritedElement(table: widgets, hydroState: hydroState);
  loadRenderObjectElement(table: widgets, hydroState: hydroState);
  loadRootRenderObjectElement(table: widgets, hydroState: hydroState);
  loadLeafRenderObjectElement(table: widgets, hydroState: hydroState);
  loadSingleChildRenderObjectElement(table: widgets, hydroState: hydroState);
  loadMultiChildRenderObjectElement(table: widgets, hydroState: hydroState);
  loadDebugCreator(table: widgets, hydroState: hydroState);
  loadIndexedSlot(table: widgets, hydroState: hydroState);
}
